### ISSUE TITLE
Is there any plan of releasing this? 

### ISSUE THREAD

**Issue by RCAPSN** [Ankeno/TaskbarInfo#1]
Dear Ankeno, 

Is there any plan of releasing this? Sound very good. @Ankeno

**Comment by Ankeno** [comment]
Hello,
I will release it next week.

**Comment by RCAPSN** [comment]
> Hello, I will release it next week.

Thanks for response so quickly. Looking forward to the 1st release!

**Comment by RCAPSN** [comment]
BTW, does this plugin work with the Windows 11 taskbar yet?

**Comment by Ankeno** [comment]
I don't know if it works for Windows 11, I don't have it yet.

**Comment by Ankeno** [comment]
Closing this as the first version of the plugin was released.
